[server]
headless = true
enableStaticServing = true
#port = 7979

[browser]
gatherUsageStats = false

[client]
showErrorDetails = "none"

[[theme.fontFaces]]
family="PT Sans"
url="app/static/PT_Sans/PTSans-Regular.ttf"

[theme]
base = "light"
headingFont = "BebasNeue"
font = "IBMPlexSans"
primaryColor = "#017FFD"